PYTHON = python
PIP = pip
PROJECT_NAME = WMS

.PHONY:  run

docker-s:
	docker-compose up -d

migrations:
	python manage.py makemigrations
	python manage.py migrate

pc:
	poetry run pre-commit run --all-files

run:
	python manage.py runserver
